import { Finding, Project, User } from "../types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    code: "PRJ-SCBD",
    name: "Proyek Tower Gedung A - SCBD",
    location: "Kaveling 52-53, Jakarta Selatan",
    createdAt: new Date("2026-01-10").toISOString(),
  },
  {
    id: "proj-2",
    code: "PRJ-CW45",
    name: "Pembangunan Jembatan Layang Ciawi",
    location: "KM 45 Tol Jagorawi, Bogor",
    createdAt: new Date("2026-02-01").toISOString(),
  },
  {
    id: "proj-3",
    code: "PRJ-RSMU",
    name: "Renovasi Rumah Sakit Medika Utama",
    location: "Jl. Pemuda No. 12, Surabaya",
    createdAt: new Date("2026-03-15").toISOString(),
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "usr-admin-1",
    name: "Hendrik Pratama (Administrator)",
    email: "admin@sitetracker.id",
    role: "ADMIN",
    phoneNumber: "0811-2233-4455",
    password: "admin",
    projectId: null,
    projectIds: ["proj-1", "proj-2", "proj-3"],
  },
  {
    id: "usr-cmd-1",
    name: "Budi Santoso (Patroli CMD)",
    email: "budi.cmd@sitetracker.id",
    role: "CMD",
    phoneNumber: "0812-3456-7890",
    password: "123",
    projectId: null,
    projectIds: ["proj-1", "proj-2", "proj-3"],
  },
  {
    id: "usr-bod-1",
    name: "Drs. Eko Prasetyo (BOD / Direksi)",
    email: "eko.bod@sitetracker.id",
    role: "BOD",
    phoneNumber: "0818-7766-5544",
    password: "123",
    projectId: null,
    projectIds: ["proj-1", "proj-2", "proj-3"],
  },
  {
    id: "usr-pm-1",
    name: "Ir. H. Hendra Gunawan (PM Multi-Proyek)",
    email: "hendra.pm@sitetracker.id",
    role: "PM",
    phoneNumber: "0811-9900-1122",
    password: "123",
    projectId: "proj-1",
    projectIds: ["proj-1", "proj-2", "proj-3"],
  },
  {
    id: "usr-sm-1",
    name: "Ir. Aris Munandar (Site Manager SCBD & Ciawi)",
    email: "aris.sm@sitetracker.id",
    role: "SM",
    phoneNumber: "0812-9988-7766",
    password: "123",
    projectId: "proj-1",
    projectIds: ["proj-1", "proj-2"],
  },
  {
    id: "usr-pic-1",
    name: "Ahmad Fauzi (PIC Site SCBD)",
    email: "ahmad.fauzi@sitetracker.id",
    role: "PIC",
    phoneNumber: "0813-8899-0011",
    password: "123",
    projectId: "proj-1",
    projectIds: ["proj-1"],
    project: MOCK_PROJECTS[0],
  },
  {
    id: "usr-pic-2",
    name: "Bambang Wijaya (PIC Site Ciawi)",
    email: "bambang.w@sitetracker.id",
    role: "PIC",
    phoneNumber: "0815-4433-2211",
    password: "123",
    projectId: "proj-2",
    projectIds: ["proj-2"],
    project: MOCK_PROJECTS[1],
  },
  {
    id: "usr-pic-3",
    name: "Deni Kurniawan (PIC Site RS Medika)",
    email: "deni.k@sitetracker.id",
    role: "PIC",
    phoneNumber: "0817-6655-4433",
    password: "123",
    projectId: "proj-3",
    projectIds: ["proj-3"],
    project: MOCK_PROJECTS[2],
  },
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "find-1",
    ticketCode: "CMD-2026-001",
    projectId: "proj-1",
    project: MOCK_PROJECTS[0],
    picId: "usr-pic-1",
    pic: MOCK_USERS[5],
    reporterId: "usr-cmd-1",
    reporter: MOCK_USERS[1],
    locationDetail: "Lantai 4 - Area Bekisting Kolom K-08 (SCBD)",
    coordinates: "-6.2241, 106.8094",
    category: "K3_SAFETY",
    description: "Ditemukan 3 pekerja subkontraktor bekerja pada ketinggian 6 meter tanpa safety harness dan tali pengaman terpasang pada lifeline.",
    photoFindingUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
    status: "OPEN",
    createdAt: new Date("2026-08-20T09:15:00Z").toISOString(),
    dueDate: new Date("2026-08-21T09:15:00Z").toISOString(),
  },
  {
    id: "find-2",
    ticketCode: "CMD-2026-002",
    projectId: "proj-1",
    project: MOCK_PROJECTS[0],
    picId: "usr-pic-1",
    pic: MOCK_USERS[5],
    reporterId: "usr-cmd-1",
    reporter: MOCK_USERS[1],
    locationDetail: "Lantai 2 - Dinding Panel Sisi Timur (SCBD)",
    coordinates: "-6.2243, 106.8091",
    category: "QUALITY",
    description: "Retak rambut sepanjang 45cm pada plesteran dinding batas timur akibat proses curing yang terlalu cepat dan kurang pembasahan.",
    photoFindingUrl: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=800&q=80",
    status: "RESOLVED",
    picResponse: "Telah dilakukan chipping area retak, pengolesan bonding agent mortar epoxy, serta finishing ulang plesteran dan curing basah selama 3 hari.",
    photoResolutionUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date("2026-08-19T14:30:00Z").toISOString(),
    dueDate: new Date("2026-08-21T14:30:00Z").toISOString(),
    resolvedAt: new Date("2026-08-20T11:00:00Z").toISOString(),
  },
  {
    id: "find-3",
    ticketCode: "CMD-2026-003",
    projectId: "proj-2",
    project: MOCK_PROJECTS[1],
    picId: "usr-pic-2",
    pic: MOCK_USERS[6],
    reporterId: "usr-cmd-1",
    reporter: MOCK_USERS[1],
    locationDetail: "Pier 3 - Saluran Drainase Sementara (Ciawi)",
    coordinates: "-6.6501, 106.8402",
    category: "KEBERSIHAN_5R",
    description: "Sisa potongan kayu bekisting dan puing semen menumpuk di saluran drainase temporary sehingga berpotensi banjir saat hujan deras.",
    photoFindingUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    status: "CLOSED",
    picResponse: "Tim 5R proyek telah pembersihan total material kayu dan semen. Saluran kini lancar kembali dan disediakan dump bin khusus.",
    photoResolutionUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80",
    createdAt: new Date("2026-08-18T08:00:00Z").toISOString(),
    dueDate: new Date("2026-08-20T08:00:00Z").toISOString(),
    resolvedAt: new Date("2026-08-18T16:20:00Z").toISOString(),
    closedAt: new Date("2026-08-19T09:00:00Z").toISOString(),
  },
  {
    id: "find-4",
    ticketCode: "CMD-2026-004",
    projectId: "proj-1",
    project: MOCK_PROJECTS[0],
    picId: "usr-pic-1",
    pic: MOCK_USERS[5],
    reporterId: "usr-cmd-1",
    reporter: MOCK_USERS[1],
    locationDetail: "Gudang Logistik Samping Gate 2 (SCBD)",
    coordinates: "-6.2245, 106.8099",
    category: "MATERIAL",
    description: "Besi beton D16 ditumpuk langsung di atas tanah tanpa alas kayu ganjal dan penutup terpal hujan, mengalami korosi permukaan ringan.",
    photoFindingUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
    status: "OPEN",
    createdAt: new Date("2026-08-21T08:45:00Z").toISOString(),
    dueDate: new Date("2026-08-23T08:45:00Z").toISOString(),
  },
  {
    id: "find-5",
    ticketCode: "CMD-2026-005",
    projectId: "proj-2",
    project: MOCK_PROJECTS[1],
    picId: "usr-pic-2",
    pic: MOCK_USERS[6],
    reporterId: "usr-cmd-1",
    reporter: MOCK_USERS[1],
    locationDetail: "Pier 2 - Area Stek Tulangan Kolom (Ciawi)",
    coordinates: "-6.6505, 106.8407",
    category: "K3_SAFETY",
    description: "Besi stek tulangan kolom abutment belum diberi safety cap (pelindung ujung besi) yang berisiko menusuk pekerja di sekitarnya.",
    photoFindingUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80",
    status: "OPEN",
    createdAt: new Date("2026-08-22T10:00:00Z").toISOString(),
    dueDate: new Date("2026-08-23T10:00:00Z").toISOString(),
  },
  {
    id: "find-6",
    ticketCode: "CMD-2026-006",
    projectId: "proj-3",
    project: MOCK_PROJECTS[2],
    picId: "usr-pic-3",
    pic: MOCK_USERS[7],
    reporterId: "usr-cmd-1",
    reporter: MOCK_USERS[1],
    locationDetail: "Lantai 1 - Koridor Rawat Inap (RS Medika)",
    coordinates: "-7.2575, 112.7521",
    category: "KEBERSIHAN_5R",
    description: "Pekerjaan pembongkaran keramik koridor tidak menggunakan barikade plastik debu sehingga partikel semen beterbangan ke area pasien.",
    photoFindingUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
    status: "OPEN",
    createdAt: new Date("2026-08-23T11:30:00Z").toISOString(),
    dueDate: new Date("2026-08-24T11:30:00Z").toISOString(),
  },
];
